### ISSUE TITLE
"Mit der Nachricht 'Ich bin nicht Dorian Nakamoto.' meldete sich Satoshi ein letztes Mal."

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#10]
Das ist unwahrscheinlich. Es gab von Satoshi-Accounts auch später noch Nachrichten, und es ist nicht klar, wer darauf alles Zugriff hat. Also es kann sein, daß das nicht Satoshi war, und es könnte auch sein, daß er sich später noch gemeldet hat. Daß das seine letzte Nachricht war, ist Spekulation.

**Comment by anitaonl** [comment]
Geändert. "Vom Account Nakamotos wurde die Nachricht "Ich bin nicht Dorian Nakamoto." versendet, womit die Spekulation vorerst beendet wurde."
