### ISSUE TITLE
"Steigt das Interesse an Bitcoin im selben Zeitraum, steigt der Preis exponentiell."

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#11]
Das geht vielleicht noch im Englischen, da heißt "exponentially" oft nur sowas wie "ziemlich stark", aber im deutschen sollte man das "exponentiell" mE lieber weglassen, denn es heißt nichts.

**Comment by anitaonl** [comment]
Stimmt.
