### ISSUE TITLE
Adressen, Wallets, Seeds in "Sichern Sie Ihr Geld"

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#13]
Da steht, man brauche drei Dinge: Wallet, Adressen, Seeds. Das finde ich verwirrend. Der ganze Abschnitt könnte klarer sein. Was meinst Du mit Wallet? Du sagst, es sei einerseits eine Software, die das alles verwaltet und andererseits ein "Schlüsselbund".  Es werden tatsächlich verschiedene Dinge damit bezeichnet. Eine Möglichkeit, das schlüssig zu bezeichnen: Eine Walletsoftware verwaltet eine Wallet. Eine Wallet enthält alles, was man zum Empfangen und Senden von Bitcoin braucht. Die Walletsoftware kann Seeds erzeugen (durch Zufall), und aus einem Seed kann man unendlich viele private Schlüssel generieren, und zu jeden privaten Schlüssel gehört ein öffentlicher Schlüssel und der entspricht einer Adresse. Eine Adresse braucht man, um Bitcoins zu empfangen. Einen privaten Schlüssel braucht man, um die Bitcoins, die man mit dieser Adresse empfangen hat, wieder auszugeben. Um diese ganze Verwaltung der Wallet (Brieftasche, besser wäre vielleicht Schlüsselbund, aber mit potentiell unendlich vielen, gratis erzeugbaren Schlüsselpaaren) kümmert sich die Walletsoftware, und man kann mithilfe eines Seeds auch jederzeit die Wallet mittels einer Walletsoftware wieder herstellen. 

Das ist tatsächlich ziemlich kompliziert, und sicher noch nicht didaktisch optimal. Aber es geht sicher besser als es jetzt ist.

**Comment by anitaonl** [comment]
Nehme zur Kenntnis, dass es verbesserungswürdig ist. Für die nächste Ausgabe.
