### ISSUE TITLE
"Hardware-Wallets, sind nicht immer online und dadurch viel sicherer."

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#14]
Das ist nicht wirklich der Punkt. Die Idee von Hardwarewallets ist, daß sie überhaupt nie online sind. Eine Hardwarewallet ist so konstruiert, daß sie nur (mit Bestätigung des Users) Transaktionen signieren kann, aber den Seed gar nicht rausgeben kann. Es sollte daher egal sein, ob sie nicht immer online ist.

**Comment by anitaonl** [comment]
Stimmt. geändert.
