### ISSUE TITLE
"Card Wallet"

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#15]
wird mehrmal erwähnt (ist das ein Sponsor?), und das ist sicher auch OK, aber man sollte schon darauf hinweisen, daß man damit den Herausgebern vertraut, den private key nicht kopiert zu haben.

**Comment by anitaonl** [comment]
Der Satz war missverständlich. "Allerdings müssen Sie den Herstellern vertrauen, dass sie die privaten Schlüssel für die Karte nicht kopieren." Steht jetzt deutlicher da.
Darunter nochmal: Der branchenweit bevorzugte Standard und die **empfohlene Cold Storage-Lösung sind Hardware-Wallets**.
