### ISSUE TITLE
"Einige Hardware-Wallets (keine der oben genannten) verwenden Bluetooth als Verbindungsmethode. Davon rate ich ab, da die Bluetooth-Technologie als relativ unsicher gilt.""

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#16]
Das sind zwei Fehler. Erstens funktioniert die Ledger Nano X (die Du empfiehlst) mit Bluetooth, und zweitens gibt es dagegen auch nicht wirklich etwas zu sagen. Bluetooth und USB gelten als ähnlich unsicher, was aber mit einem korrekten HW-Wallet-Design auch nicht schlimm sein sollte (weil HW-Wallets halt nur signieren können sollten). Wenn man davor Angst hat, hilft nur QR-Codes oder andere echte offline-Methoden.

**Comment by anitaonl** [comment]
Stimmt. Absatz gelöscht.
