### ISSUE TITLE
Learning by Doing

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#17]
"Die beste Zeit dafür ist in der Regel das Wochenende...". Das stimmt schon irgendwie, aber heutzutage würde ich doch eher dazu raten, gleich mit Lightning anzufangen, wenn man mit kleinen Beträgen rumspielen möchte.

**Comment by anitaonl** [comment]
Das stimmt schon, aber hier beziehe ich mich auf Bitcoin Transaktionen.
