### ISSUE TITLE
"Wenn der Betrag auf der Hardware-Wallet wie bestätigt angekommen ist"

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#18]
Auch hier gibt es wieder diese (übliche) Mehrdeutigkeit von Wallet. Hardware-Wallets können im Allgemeinen nicht prüfen, ob eine Transaktion angekommen ist. Das können nur nodes, die von Walletsoftware gefragt werden. Hardware-Wallets können eigentlich nur Transaktionen signieren.

**Comment by anitaonl** [comment]
Habe "wie bestätigt" gelöscht.
