### ISSUE TITLE
"Der aktuelle Preis einer Ware auf einem freien Markt ist der Durchschnitt der Preise, auf die sich die Menschen in der Vergangenheit tatsächlich geeinigt und gehandelt haben."

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#19]
Nein.

**Comment by anitaonl** [comment]
Sehr vereinfachte Formulierung.....Wäre es richtiger zu sagen: 

Der aktuelle Preis eines Guts (wie Bitcoin) auf einem freien Markt ist der Durchschnitt der Preise, auf die sich die Menschen in der Vergangenheit tatsächlich geeinigt und gehandelt haben.

**Comment by stefanwouldgo** [comment]
Nein, es ist gar kein Durchschnitt, sondern eher der LETZTE Preis, auf den
sich Leute geeinigt haben.

Anita Posch ***@***.***> schrieb am Di., 22. Feb. 2022, 16:56:

**Comment by anitaonl** [comment]
Danke! Geändert: Der aktuelle Preis einer Ware auf einem offenen Markt ist der zuletzt vereinbarte Preis, zu dem tatsächlich gehandelt wurde.
