### ISSUE TITLE
"Aber seien Sie vorsichtig, denn einige Geldautomatenbetreiber verlagen überdurchschnittlich hohe Gebühren."

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#20]
Das scheint mir etwas verkehrt. Es ist vielmehr so, daß die MEISTEN Geldautomatenbetreiber hohe Gebühren verlangen (weil sie es können, weil die Leute keine andere Möglichkeit haben, weil sie Kosten haben, was weiß ich, jedenfalls gibt der Markt es scheinbar her). Deshalb ist der Durchschnitt der Gebühren an solchen Automaten einfach hoch.

**Comment by anitaonl** [comment]
von "einige" in "viele" Geldautomatenbetreiber geändert.
