### ISSUE TITLE
ifyouhadboughtcryptodotcom

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#21]
Warum dieser link? War da vielleicht mal eine andere Webseite? Die aktuelle sagt einfach, daß "Crypto" kaufen immer geil ist. Also ungefähr das Gegenteil von dem, was Du aussagen willst.

**Comment by anitaonl** [comment]
Stimmt. Früher konnte man Bitcoin und Altcoins vergleichen und das Ergebnis war oft besser für Bitcoin. Habe es gelöscht.
