### ISSUE TITLE
"DeFi bietet eine zuverlässigere Alternative"

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#22]
Echt jetzt? Was ist denn hiermit: https://cryptosec.info/defi-hacks/ ? DeFi ist wilder Westen und hat jede Menge crazy Risiken. Das ist OK, wenn man das weiß, aber das hier als sichere Alternative zu zentralen Börsen darzustellen, scheint mir nicht sehr korrekt. Sponsoring hin oder her, aber soviel Ehrlichkeit muß sein.

**Comment by anitaonl** [comment]
Da ist die Übersetzung leider falsch! Englisch: "DeFi offers a more trustless alternative" sagt was anderes aus.

DeFi bietet eine Alternative durch die Verwendung von Smart Contracts, eine Art programmierter Ablauf beispielsweise für Kauf- oder Tauschverträge.
