### ISSUE TITLE
"Mehrheitskonsens"

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#5]
In "Wie entstehen Bitcoin" ist von "Mehrheitskonsens" zur Änderung der Regeln die Rede. Das ist verwirrend, weil es nach Wahlen klingt. So etwas gibt es in Bitcoin aber nicht. Vielleicht einfach durch "Konsens" ersetzen?

**Comment by anitaonl** [comment]
Danke. Geändert.
