### ISSUE TITLE
"... und soll Miner davon abschrecken, Transaktionen in ihrem Sinne zu verändern."

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#8]
Miner können keine Transaktionen verändern (außer ihre eigenen). Siehe auch https://github.com/anitaposch/learn-bitcoin/issues/7

**Comment by anitaonl** [comment]
geändert in: Diese dient den Minern als Anreiz, den Regeln des Netzwerks zu folgen und soll sie davon abhalten, sich mit anderen zusammen zu schließen und das Netzwerk zu attackieren.
