### ISSUE TITLE
UTXO-Erklärung in "Bitcoin, eher nicht Bitcoins, aber niemals BitCoin"

### ISSUE THREAD

**Issue by stefanwouldgo** [anitaposch/learn-bitcoin#9]
"Dies ist die Menge der Einheiten, die an einer bestimmten Bitcoin-Adresse verzeichnet ist.". Das stimmt nicht so ganz. Mehrere UTXOs können die gleiche Adresse haben. Adressen sind überhaupt nur eine seltsame Abstraktion, nämlich Hashes von so Dingen wie Output-Skripten oder Public Keys. UTXOs sind tatsächlich die Punkte, die Bitcoins enthalten, und die haben verschiedene Eigenschaften, so wie etwa Adressen.

**Comment by anitaonl** [comment]
Übernommen.
